language: scala

scala:
   - 2.12.8
   - 2.13.0

matrix:
  allow_failures:
    - scala: 2.13.0

script:
  - sbt coreJVM/test server/webStage

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: server/target/web/stage
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master